### ISSUE TITLE
Failed to generate single outFile

### ISSUE THREAD

**Issue by 1tchy** [ArpNetworking/sbt-typescript#1]
The option `outFile` doesn't seem to create the expected single JS-file.
Although if this option is specified, all other JS-files are not created.

Following you can find an example based on the "complicated"-Test:

build.sbt:

```
import com.arpnetworking.sbt.typescript.Import.TypescriptKeys._

lazy val root = (project in file(".")).enablePlugins(SbtWeb).settings(
  JsEngineKeys.engineType := JsEngineKeys.EngineType.Node,
  outFile := "myfile.js",
  outDir := "path"
)

libraryDependencies += "org.webjars" % "bootstrap" % "3.0.2"
```

test:

```
> assets
$ absent target/web/typescript/main/javascripts/animal.js
$ absent target/web/typescript/main/javascripts/mammal.js
$ absent target/web/typescript/main/javascripts/human.js
$ exists target/web/typescript/path/myfile.js
```

**Comment by BrandonArp** [comment]
Thanks for the report. It's going to be a bit tricky to get this solved.  It looks like the built-in jsengine tasks aren't well suited for this kind of task (multiple source files to generate a single output file).  I'm going to have to think about how to make this work.  If you have any ideas, please let me know.

**Comment by 1tchy** [comment]
I'm not really into it. But it looks like the [sbt-concat](https://github.com/ground5hark/sbt-concat)-plugin does something similar. Maybe you can have a look there.

**Comment by fernandezpablo85** [comment]
You can use both sbt-concat and this plugin to generate the single js file you want.

**Comment by BrandonArp** [comment]
@1tchy Are you still wanting this feature? With the work done on 0.1.5 I think it's now possible to do it, but I'd rather not spend time on the feature if nobody will use it.

**Comment by 1tchy** [comment]
Thanks for asking. I would have used it for a specific project, however this project is done and so I currently have no more need for this.

**Comment by joost-de-vries** [comment]
This would be a very useful feature. Do you have an idea what needs to be done? I can add a helping hand.

**Comment by akauppi** [comment]
Today's the 1st birthday of this issue! :cake:

**Comment by rockneurotiko** [comment]
Yay!!!! :cake:
