### ISSUE TITLE
Update to TypeScript 1.5.3

### ISSUE THREAD

**Issue by mickeyvip** [ArpNetworking/sbt-typescript#11]
Hello and thank you.

Can you please update the plugin to TypeScript version `1.5.3`?

Thank you.

**Comment by BrandonArp** [comment]
Released to central as 0.1.7.  Please let me know if you have any problems.

**Comment by mickeyvip** [comment]
Hello.

Testing it now (no config, defaults). I have 1 file:
`app/assets/javascripts/app.ts`

I see it is compiled and copied into
`target/web/typescript/main/javascripts/app.js`

With that I see `app.ts` is also copied into:
`target/web/public/main/javascripts/app.ts`

So referencing `app.js` in 'main.scala.html':
`<script src="@routes.Assets.versioned("javascripts/app.js")"></script>`

gives `404`.

Is this it is supposed to be?

I see that `coffeescript` file `test.coffee` is copied into:
`target/web/coffeescript/main/javascripts/test.js`
and also into:
`target/web/public/main/javascripts/test.js`.

**Comment by mickeyvip** [comment]
Strangely enough after I have added `test.coffee` file, the compilation started to copy `app.js` to:
`target/web/public/main/javascripts/app.js`

and continued even when I removed the `test.coffee`.

But enabling sourceMaps in `build.sbt`:
`TypescriptKeys.sourceMap := true`

does not copy the `app.js.map` to:
`target/web/public/main/javascripts/app.js.map`

but only to 
`target/web/typescript/main/javascripts/app.js.map`

with that the `app.ts` is missing from:
`target/web/typescript/main/javascripts/`

**Comment by mickeyvip** [comment]
It seems that the transpiled `.js` files are not copied to the `public` folder on Windows

**Comment by BrandonArp** [comment]
That might be caused by #5.  Do you have a non-windows box to test on?

**Comment by mickeyvip** [comment]
On non Windows I see that all is Ok except that `.map` file is not copies into `target/web/public/main/javascripts/` folder.

**Comment by BrandonArp** [comment]
Would you mind filing an issue about the .map file problem?  I'd love to tackle that as a separate issue.

**Comment by mickeyvip** [comment]
I have just opened an issue on source maps. 

Thank you.
