### ISSUE TITLE
Source maps are not copied to the "public" folder

### ISSUE THREAD

**Issue by mickeyvip** [ArpNetworking/sbt-typescript#13]
I am using the plugin with the following settings in `build.sbt`:

``` scala
JsEngineKeys.engineType := JsEngineKeys.EngineType.Node

TypescriptKeys.sourceMap := true
```

and I have those files under `app/assets/javascripts`:
`app.ts`
`app-coffee.coffee`
![image](https://cloud.githubusercontent.com/assets/220427/9774786/6991ac9e-5753-11e5-8626-4766b128ff15.png)

After the project is compiled I see that the correct files are copied to `typescript` folder:
![image](https://cloud.githubusercontent.com/assets/220427/9774819/ae40f188-5753-11e5-9b82-d95f37acd1db.png)

similar to `coffeescript` folder:
![image](https://cloud.githubusercontent.com/assets/220427/9774827/bdedd3da-5753-11e5-81b1-4ee02d64aa0a.png)

but the `map` file is not copied into `public` (there is only 1 `map` for `app-coffee.coffee`):
![image](https://cloud.githubusercontent.com/assets/220427/9774844/d59892d6-5753-11e5-9d85-a406eec4f389.png)

**Comment by mickeyvip** [comment]
Thank you so much!

Are you releasing this as `v0.1.8`?

**Comment by BrandonArp** [comment]
I just cut the 0.1.8 release.  It should be in central in a few minutes.

**Comment by mickeyvip** [comment]
Working!

Thank you!
