### ISSUE TITLE
Possible upgrade to Scala 2.11

### ISSUE THREAD

**Issue by mickeyvip** [ArpNetworking/sbt-typescript#17]
Hello.

This plugin uses Scala `2.10`.

Scala `2.11` was released for some time now.

I was wondering if this plugin can be updated/forked to use Scala `2.11.x`.

Thank you.

**Comment by BrandonArp** [comment]
If I understand things correctly, the version of scala used has to be the same as is used by sbt.  As far as I know, sbt is only using scala 2.10 right now.  Do you know of a version of sbt using 2.11?  Is this causing you other problems?  Please let me know.

**Comment by mickeyvip** [comment]
Hello.

`sbt` needs Scala `2.10.x` indeed.

Sorry.
