### ISSUE TITLE
The options lack new modules format support

### ISSUE THREAD

**Issue by mickeyvip** [ArpNetworking/sbt-typescript#18]
Although the new version uses `1.6.2` compiler - it lacks new features.

One of them is more module formats:

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2073

``` javascript
export const enum ModuleKind {
    None = 0,
    CommonJS = 1,
    AMD = 2,
    UMD = 3,
    System = 4,
}
```

Also, it seems from their example that you don't need to use numeric constants, there is an Enum for modules:

``` javascript
import * as ts from "typescript";
/// ...
let commonJsModule = ts.ModuleKind.CommonJS;
let systemModule = ts.ModuleKind.System;
```

Thank you.

**Comment by laguiz** [comment]
This issue may help : https://github.com/ArpNetworking/sbt-typescript/issues/23

**Comment by mickeyvip** [comment]
My PR that adds new modules was merged.
