### ISSUE TITLE
Taking an extremely long time to compile

### ISSUE THREAD

**Issue by fernandezpablo85** [ArpNetworking/sbt-typescript#2]
it takes about 50 seconds to compile a single, ~100 LOC typescript file, without source maps.

Same file takes less than a second in the terminal running tsc. Any idea what's happening?

**Comment by BrandonArp** [comment]
Hi Pablo, thanks for reporting the issue.  My first thought is that NodeJS isn't doing the compiling.  Try adding  JsEngineKeys.engineType := JsEngineKeys.EngineType.Node  to your build.sbt file.  If this doesn't help, let me know and we'll figure it out.

**Comment by fernandezpablo85** [comment]
yes that reduced the compile time dramatically. It would be nice for the README to warn about this, I can submit a PR if you want to.

**Comment by BrandonArp** [comment]
I would love a PR for additional documentation.  Also, I will try to update the code a bit to use Nashorn instead of Rhino if running Java 8.  I've heard that 8u40 is supposed to have much better speed (close to NodeJS).

**Comment by fernandezpablo85** [comment]
Doc PR coming up:

https://github.com/ArpNetworking/sbt-typescript/pull/4

**Comment by fernandezpablo85** [comment]
If you need any help on the Nashorn migration please let me know. I'm not familiar with it but if you point me in the right direction I might be of use :smile:
