### ISSUE TITLE
Options for AngularJS 2

### ISSUE THREAD

**Issue by hseeberger** [ArpNetworking/sbt-typescript#23]
How can I set options needed for AngularJS 2:

```
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    ...
```

**Comment by laguiz** [comment]
I'm also interested in this for angular2. 

Could it be possible to provide the `tsconfig.json` file? https://github.com/Microsoft/typescript/wiki/tsconfig.json

**Comment by BrandonArp** [comment]
@laguiz I really like the idea of using the tsconfig.json file.  It looks like a great way to leverage the TS compiler more directly.  Unfortunately, I don't have the time to do this right now.  Would you be interested in doing this work?

**Comment by laguiz** [comment]
I may give it a try without guaranty (not sure to have time).

Here is what I would think to do (as a first shot) : 
1. In https://github.com/ArpNetworking/sbt-typescript/blob/master/src/main/scala/com/arpnetworking/sbt/typescript/SbtTypescript.scala add a boolean to activate the use of the config file
2. At https://github.com/ArpNetworking/sbt-typescript/blob/master/src/main/resources/typescriptc.js#L165 read an extra parameter that provide the **content** of the json config file as a string. (not sure yet about the relations between `args` and actual options in sbt plugin)
3. Find a way to provide the config to the compiler with minimum understanding of the file (providing options from the json file without understanding would be ideal but i'm not sure it's possible with `createCompilerHost()`). This is where I may need some guidance from you.

If this works we can give more options like direct path to the config, etc.

**Comment by laguiz** [comment]
@BrandonArp Hi, here is a working commit that enable the support for `tsconfig.json` : 
https://github.com/laguiz/sbt-typescript/commit/63ebb18e8e9167c9197fa66eee8a6d969eec8177

I simplified the logic : 
1. If `tsconfig.json` file exist (in root folder of the project) then use it for init
2. After init with `tsconfig.json` then we apply sbt options but only the ones that does not already exist in `tsconfig.json` file (For me it the easiest way to reason about it).
2. If `tsconfig.json` file does not exist then skip it

You can test with `scripted sbt-typescript-plugin/tsconfig` and `scripted sbt-typescript-plugin/simple`.

Let me know your feedback and if you want me to send a pull request.

I hope you have time to follow this.

**Comment by v7r7** [comment]
Hey @BrandonArp I am expressing interest in @laguiz's patch to be a new feature for this plugin, roughly when might this be possible?

**Comment by laguiz** [comment]
For those interested I quickly published a version with this change included.

## How to try?
1. Add a maven repository with this url in `project/plugins.sbt` : 
   
   ```
   repositories += "Bintray Warmax Maven" at "http://dl.bintray.com/warmax/maven"
   ```
2. Still in `project/plugins.sbt` replace your existing declaration with this 
   
   ``` bash
   addSbtPlugin("com.laguiz" % "sbt-typescript" % "0.1.10")
   ```
3. In **root** folder of you sbt project add a file named `tsconfig.json`. For example : 
   
   ``` json
   {
    "compilerOptions": {
      "target": "ES5",
      "module": "commonjs",
      "sourceMap": true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "removeComments": false,
      "noImplicitAny": true,
      "suppressImplicitAnyIndexErrors": true
   }
   }
   ```

I won't maintain this project... it's only here for those that want to try. However feel free to give feedback.

**Comment by alexqyle** [comment]
@laguiz I got this "org.scalaz.stream#scalaz-stream_2.10;0.7a: not found" when importing this plugin.

**Comment by v7r7** [comment]
I also run into 

[error](*:update) sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.10;0.7a: not found

**Comment by laguiz** [comment]
I'm not able to reproduce your issue :/.
1. Did you make `addSbtPlugin("com.arpnetworking" % "sbt-typescript" % "0.1.9")` work before trying my version? Stange thing is that my commit focus only on `typescriptc.js` so it should not do anything more than the original version of this plugin regarding dependencies.
2. It works for me if I create a fresh `play-java` project with activator 1.3.6 (Just downloaded here https://www.playframework.com/download).
3. What's your config?
   - What version of sbt are you _using_ (run `sbt sbtVersion` or `./activator --version`)? 
   - What version of sbt is _declared_ in `cat project/build.properties | grep version`?
   - What version is _declared_ in your `build.sbt` ?

If you can, update your sbt, activator and java versions.

**Comment by alexqyle** [comment]
@laguiz I cleaned 0.1.9 in both .ivy2 and in my project. And import 0.1.10 from your repo again. I still got the same error.

I am using sbt 0.13.5 same as the version defined in build.properties. And the scala version is 2.11.4 in build.sbt.

**Comment by laguiz** [comment]
Are you able to upgrade your sbt version to `0.13.9` and scala to `2.11.6` ? Just to see if it's better.

**Comment by laguiz** [comment]
@shadow999 if I search on my computer I don't find any reference to this jar.

Maybe this repo can help : https://bintray.com/pchiusano/maven/scalaz-stream/0.7a/view#files/org/scalaz/stream/scalaz-stream_2.11/0.7a

Do you use activator? If yes what version? I'm using activator `activator-1.3.6-minimal` and I also tested with `activator-1.2.12-minimal`.

Let me know if you have make any progress.

**Comment by alexqyle** [comment]
@laguiz I tried to compile your change into jar. And use that jar as sbt-typescript plugin. It seems everything works fine. But it takes longer time to compile ts file than before. I am not sure if it caused by that I compiled the plugin by myself.

**Comment by laguiz** [comment]
@shadow999 I don't see why time to compile would be slower. Note that my code is based on current master branch. How slower?

**Comment by alexqyle** [comment]
@laguiz After a simple investigation, I found out the slowness was caused by reading tsconfig.json file. Here is how I tested it:
My typescript files need "module" flag to be set.
I compiled my typescripts without any options nor tsconfig.json. It took 10 seconds to show the compile error.
Then I added tsconfig.json with some options except "module". It took more than two minutes to show the compile error.

NOTE: In both case, I used the same plugin binary which includes your fix.

**Comment by laguiz** [comment]
@shadow999 We read the file from javascript and we marge the content of this file with existing options. I will try investigate into this when I have time. Feel free to try to debug by comparing test projects `scripted sbt-typescript-plugin/tsconfig` and `scripted sbt-typescript-plugin/simple`.
