### ISSUE TITLE
Unresolved dependencies with 0.1.9 and 0.1.8

### ISSUE THREAD

**Issue by hseeberger** [ArpNetworking/sbt-typescript#24]
```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe#jstranspiler;1.0.0: not found
[error] unresolved dependency: com.typesafe#jse_2.10;1.0.0: not found
[error] unresolved dependency: com.typesafe#npm_2.10;1.0.0: not found
```

**Comment by huntc** [comment]
Resolver issue?

**Comment by hseeberger** [comment]
The README doesn't mention any special resolvers. Which one do you suggest to add, @huntc?

**Comment by huntc** [comment]
I shall look into it

**Comment by huntc** [comment]
Here it is: https://repo.typesafe.com/typesafe/maven-releases/com/typesafe/jstranspiler/1.0.0/

**Comment by hseeberger** [comment]
Thanks. So the README needs to be updated to include `resolvers += "Typesafe Repository" at "https://repo.typesafe.com/typesafe/maven-releases"` in `plugins.sbt`.

**Comment by huntc** [comment]
Thanks. Updated the README: https://github.com/typesafehub/jstranspiler#jstranspiler

**Comment by BrandonArp** [comment]
I think this issue has been resolved. Please re-open if the README is still unclear.
