### ISSUE TITLE
Update bundled typescript version to 1.4

### ISSUE THREAD

**Issue by fernandezpablo85** [ArpNetworking/sbt-typescript#3]
Most header files in `definitely typed`[1] use "union types" which are > 1.4, it would be great to have support for the latest 1.4 version in this plugin.

[1] http://definitelytyped.org/

**Comment by legacycode** [comment]
+1 That would be great. I have the same problem. When using the bootbox.d.ts 4.4.4, jquery or knockout definition files i get a typescript compilation error from the plugin. Unfortunately I do not understand the scala syntax.

**Comment by mtidei** [comment]
+1 I'd appreciate 1.4, too. Could you please rebuild this plugin with the newest typescript compiler? Want to avoid forking just for updating a dependency... Thank you!

**Comment by fernandezpablo85** [comment]
it's not just bumping a dependency but a significantly harder change
because the compiler APIs are different.

**Comment by BrandonArp** [comment]
For those that +1'd this issue, does moving to 1.5-beta work for you?  I was having a really difficult time with the 1.4 APIs getting the compiler to write the files to the correct place.

**Comment by BrandonArp** [comment]
Haven't heard back on this, so I'm going to close it.  The latest version uses the 1.5-beta TypeScript release.
