### ISSUE TITLE
How to use with webjars ?

### ISSUE THREAD

**Issue by benoit-ponsero** [ArpNetworking/sbt-typescript#31]
Hello,

I am trying to test this plugin with angular2 webjar dependency but the typescript compiler never found lib files.

Perhaps there is missing some paths like they have in sbt-less plugin : 

`"paths" -> JsArray(
        (sourceDirectories.value
            ++ resourceDirectories.value
            ++ webModuleDirectories.value
            ++ nodeModuleDirectories.value)
          .map(f => JsString(f.getAbsolutePath)).toVector
      )`

any ideas ?

**Comment by jvanbruegge** [comment]
@wassertim told me, that this is a known issue.
Would be a very useful feature though

**Comment by wassertim** [comment]
Guys, this is now in master you can checkout and give it a try
