### ISSUE TITLE
Compiling of Angular2 source not working

### ISSUE THREAD

**Issue by jvanbruegge** [ArpNetworking/sbt-typescript#33]
Hi,
when I try to compile my Angular2 code I get the following error:
`cannot find module 'angular2/core`
when I try to have the node_modules folder in the "assets" folder, the plugin tries to compile it too, and I cant get a proper exclude rule to work.
A bit on that would be very helpful.

**Comment by BrandonArp** [comment]
In general, I try to encourage people to use webjars for dependencies.  Have you tried using the webjar for angular2?

**Comment by jvanbruegge** [comment]
I added angular2 and its dependencies to the library dependencies, but still the same errors on the build.
Do I have to do more than that?
EDIT: Forgot to mention, also added them in index.scala.html via reverse routing

**Comment by jvanbruegge** [comment]
So basicly this is now a duplicatate of #31.
More informatition on that should be in the Readme

**Comment by wassertim** [comment]
It is known issue. You can't use webjars as modules with the current version of sbt-typescript.

**Comment by wassertim** [comment]
More on that: you can't entirely replace node_modules with web jars. Some node modules don't have the corresponding webjars.

**Comment by jvanbruegge** [comment]
That wouldn't have bern an issue, the ones I needed were available.

Then back to my original Question, how do I get an ExcludeFilter to work? I tried a simpleFilter but it did nothing (sorry, but I'm not familiar with scala)

EDIT: And for the known issue: Isn't it possible to include libraries from target/web/lib (I think thats the correct path, but not sure), because thats where the Webjars extract to? I would try it by myself, but I neither know scala nor sbt to do it.

**Comment by wassertim** [comment]
Why do you want to put node_modules to assets and not to the project's root?

**Comment by jvanbruegge** [comment]
I dont want to, but the last time i tried it didnt work, same compiler errors, will try now again.

**Comment by wassertim** [comment]
Yes, try it again, and let me please know how it went.

**Comment by jvanbruegge** [comment]
No, still the same, I got all dependencies in /node_modules and sbt-typescript ist not able to compile.

**Comment by wassertim** [comment]
Please commit your changes and share a link

**Comment by jvanbruegge** [comment]
what changes do you mean?

**Comment by wassertim** [comment]
I meant your project where you test all these

**Comment by jvanbruegge** [comment]
It's a private repo, I added you as collaborator

**Comment by wassertim** [comment]
Ok. I'll take a look and let you know what I find out.

**Comment by jvanbruegge** [comment]
On Windows you can use Start.bat to set everything up

**Comment by wassertim** [comment]
Your project compiles just fine. You forgot to reference es6-shim typings, that's all

**Comment by jvanbruegge** [comment]
Thanks a lot!

**Comment by bpervan** [comment]
Hi guys,

what's the final solution? Same scenario, trying to use angular2 (typescript) with play2, can't make plugin recognize WebJar angular2 dependencies, can't exclude node_modules folder from compilation if I use npm.

Cheers,
Branimir

**Comment by wassertim** [comment]
The solution would be not to put the `node_modules` into the `assets` folder. So the node modules will not be added to the compilation. You should put only your source files in the `assets` folder.

**Comment by jvanbruegge** [comment]
I created a Template from my project, you can find it here: https://github.com/SuperManitu/Play2-Angular2-Template
EDIT: It's basicly the angular2 quickstart together with Play

**Comment by bpervan** [comment]
Thanks :)

**Comment by benoit-ponsero** [comment]
Hello,
I cloned your project. 
It is completely useless. You have library dependencies in package.json for compiling the *.ts files and same library dependencies in build.sbt (webjars) for serving libs.

**Comment by jvanbruegge** [comment]
the ones in the package.json are for the typescript compiler, the webjars for delivering them. That's intended, not useless

**Comment by wassertim** [comment]
> It is completely useless. You have library dependencies in package.json for compiling the *.ts files and same library dependencies in build.sbt (webjars) for serving libs.

You are right. But for now it is the only solution. We should wait until typescript 2.0 when it supports custom resolution paths. Then we will adjust the typescript plugin and see if it solves the problem.

**Comment by wassertim** [comment]
The typescript compiler does not know about web-jars directory :( And currently there is no way to set this up.

**Comment by BrandonArp** [comment]
Can you clarify what you mean here?  Are you looking to have webjars contain ts files and compile against them?

**Comment by wassertim** [comment]
This is about the module resolution. Typescript will not look at the webjars folder for `angular2/core`

**Comment by bpervan** [comment]
I'm confirming that @SuperManitu s template works. Like @wassertim said, it looks like this is so far the only way to go, given that Typescript compiler cannot be provided with custom resolution path like folder where Play2 extracts WebJars (therefore need for node_modules in the root of the project).
