### ISSUE TITLE
Incremental transpile to one file

### ISSUE THREAD

**Issue by Phivan** [ArpNetworking/sbt-typescript#36]
I want my Typescripts files to be transpiled to a main.js file into 

/target/web/public/main/webapp/js/

So here how I handle it : 
`TypescriptKeys.outFile := ((webTarget in Assets).value / "public" / "main" / "webapp" / "js").absolutePath++"/main.js"`

It works well actualy, but everytime I made a change on one of my Ts files, the plugin transpile only this file to my main.js ...

How can I fix it ?

**Comment by wassertim** [comment]
It is a well-known issue. You can contribute or wait until it is fixed. It is going to be fixed, but I can't say when :)

**Comment by wassertim** [comment]
The fix is already in master @Phivan
