### ISSUE TITLE
Tsconfig support

### ISSUE THREAD

**Issue by wassertim** [ArpNetworking/sbt-typescript#43]
We should support tsconfig eventually. Here is why:
- There are at least 2 configs in an app (one for karma tests via npm `tsconfig.json` and one for sbt `build.sbt`)
- All the mappings and other settings that exist in tsconfig usually exist in build.sbt as well

It is not good especially for big projects that you have to set the same configuration setting in 2 places.

The solution would be to use tsconfig as a default configuration which could be overridden in build.sbt.

What do you think?

**Comment by BrandonArp** [comment]
I think you're absolutely correct.  I've run into the same thing with the SBT Docker plugin.  When I started this plugin, there was only the command line configuration.  Now that there is a config file, I want people to be able to use as many of the native tools/config that they can.  Unfortunately, I don't really know when I would have the time to dive into this.

**Comment by wassertim** [comment]
I will do this
