### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by djx314** [ArpNetworking/sbt-typescript#47]
When I upgrade to sbt-typescript 0.3.1, after config complete. I execute run in my play project. Then the sbt catch an exception.

``` scala
[error] (enuma-url/web-assets:typescript) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /home/djx314/pro/workspace/enuma/enuma-url/target/typescript/typescriptc.js:17
[error] class Logger {
[error] ^^^^^
[error] 
[error] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
[error]     at exports.runInThisContext (vm.js:53:16)
[error]     at Module._compile (module.js:373:25)
[error]     at Object.Module._extensions..js (module.js:416:10)
[error]     at Module.load (module.js:343:32)
[error]     at Function.Module._load (module.js:300:12)
[error]     at Function.Module.runMain (module.js:441:10)
[error]     at startup (node.js:139:18)
[error]     at node.js:968:3
[error] Total time: 1 s, completed 2016-9-25 21:11:02
```

And I take a look at the typescript.js. It seems that lost the `"use strict";` in the top of the file.

``` javascript
class Logger {
    constructor(logLevel) {
        this.logLevel = logLevel;
    }
```

I think it should be(I am not good at javascript)

``` javascript
"use strict";
class Logger {
    constructor(logLevel) {
        this.logLevel = logLevel;
    }
```

Any fix or workaround?

**Comment by djx314** [comment]
Now I add `"use strict";` and it throw an other exception

``` scala
[info] TypeScript compiling on 57 source(s)
[error] /home/djx314/pro/workspace/enuma/enuma-url/target/typescript/typescriptc.js:132
[error]     let createProblem = (diagnostic, lineCol = {line: 0, character: 0}, fileName = 'Global', lineText = '') => {
[error]                                              ^
[error] 
[error] SyntaxError: Unexpected token =
[error]     at exports.runInThisContext (vm.js:53:16)
[error]     at Module._compile (module.js:373:25)
[error]     at Object.Module._extensions..js (module.js:416:10)
[error]     at Module.load (module.js:343:32)
[error]     at Function.Module._load (module.js:300:12)
[error]     at Function.Module.runMain (module.js:441:10)
[error]     at startup (node.js:139:18)
[error]     at node.js:968:3
```

Now I use nodejs 4.4.3 and I have tried to use Trireme but it failed any way.

**Comment by wassertim** [comment]
Why don't you update node?

**Comment by wassertim** [comment]
Sorry, you should have at least the version 6.6.0 of node: http://node.green/

**Comment by djx314** [comment]
OK, I will have a try. Beacuse debain's deb repo cannot install node 6.6.0, I will goto https://nodejs.org and have a try. Thanks.

**Comment by djx314** [comment]
But BTW @wassertim ,should it be emphasized in Readme.md?
Because I use

``` scala
com.typesafe.sbt.jse.JsEngineImport.JsEngineKeys.engineType := com.typesafe.sbt.jse.JsEngineImport.JsEngineKeys.EngineType.Trireme
```

And it will compile failed.
That the reason that I create this issue.

**Comment by wassertim** [comment]
Yes you are right … I will update the readme. Sorry for the confusion.

**Comment by djx314** [comment]
Already upgrade node to 6.6.0 and the problem really fixed. Thanks a lot for the greate pull request.
And just an idea. Typescript is es6 + type. How about change typescriptc.js to typescriptc.ts. And compile it when package this plugin with target `"es3"`, then I think the java js engine will work well.

**Comment by wassertim** [comment]
Yeah, I already thought about using typescript inside the plugin. I will try to implement this. Thanks for reporting the issues.

**Comment by wassertim** [comment]
I created 2 issues: https://github.com/ArpNetworking/sbt-typescript/issues/49, https://github.com/ArpNetworking/sbt-typescript/issues/48 so you can follow them.

**Comment by wassertim** [comment]
this will fix the Trireme usage: https://github.com/ArpNetworking/sbt-typescript/pull/50
