### ISSUE TITLE
Installation feels a bit unclear.

### ISSUE THREAD

**Issue by lenis0012** [ArpNetworking/sbt-typescript#52]
So, after reading the README documentation, i'm a bit cvonfused as to how to install this plugin properly.

From what i understand, you add the plugin to plugins.sbt, add SbtWeb to your build.sbt, and you put a tsconfig.json in your assets folder.

After doing this and playing around with the assets, it seems to compile them into a sub directory of assets, which then shows up in your public directory.

What i don't understand, is why it still keeps the .ts file, even in /public
I excpected was for it to compile all my .ts files down into my specified web.js, which i then import in the HTML.

I feel like i am doing something wrong here.

**Comment by wassertim** [comment]
Sorry for the confusion in the README. The sbt-typescript copies the .ts files to the public folder in order they can be reached with source mapping. Feel free to change the documentation and create a pull request.

**Comment by BrandonArp** [comment]
Updated in #58.
